### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by petrparolek**
- update composer to v2 in CI
- upgrade PHPStan

### CODE REVIEW

**Comment by dakorpar** [comment]
build is failing...

**Comment by petrparolek** [comment]
@dakorpar could you help me with fixing?

**Comment by dakorpar** [comment]
I have in plan to raise min php version to 7.4 here and at that point I will raise coding standards and phpstan version, currently I do not have time for this and I see this as low priority...

**Comment by f3l1x** [comment]
contributte/qa is almost ready to use. There are prepared rulesets. Pick one. :-)

**Pull request closed without merging**
