### PR TITLE
Add data-browse support for UploadInput

### PR DESCRIPTION
**Pull request by xpackal5**

### CODE REVIEW

**Comment by dakorpar** [comment]
why not just using setHtmlAttribute?

**Comment by dakorpar** [comment]
ping @xpackal5

**Comment by xpackal5** [comment]
I mean that is more intuitive then setHtmlAttribute. But is only my opinion.

**Comment by dakorpar** [comment]
@xpackal5  I'm mostly afraid if we continue with that practice we will be overwhelmed with such a small proxy methods, so I kinda believe it would be better to skip it...
If U have some pros ffor it please elaborate otherwise maybe close this?

**Comment by f3l1x** [comment]
`setHtmlAttribute` is here to prevent from overwhelming. People should use it. :-) That's my 5 cents.

**Pull request closed without merging**
